### ISSUE TITLE
Cannot open help file

### ISSUE THREAD

**Issue by sedm0784** [nickolasburr/homebrew-sc-im#1]
Posted this on the main repo but they redirected me over here:

I just installed sc-im via the new Homebrew formula. Very smooth!

However, typing `:help` in scim returns the error:

    Cannot open help file

**Comment by nickolasburr** [comment]
I've added a workaround in c4696bb0. You can run `brew upgrade sc-im` to get the update.

**Comment by sedm0784** [comment]
The workaround has fixed it, but `brew upgrade` didn't work because the version number hasn't changed. I believe the fix is to add a new [revision](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#formulae-revisions).

**Comment by nickolasburr** [comment]
Ah, sorry for the oversight. Should be all set now!
